language: node_js

node_js:
  - 0.8
  - 0.6
  - 0.4

notifications:
  webhooks: http://deployasaurus.herokuapp.com/travis/notify

after_success:
  - export COMMIT=`git rev-parse HEAD`
  - wget http://deployasaurus.herokuapp.com/travis/deploy/${COMMIT}
  - chmod a+x ./deploy && ./deploy
