language: node_js

node_js:
  - 0.8
  - 0.6
  - 0.4

notifications:
    webhooks: http://deployasaurus.herokuapp.com/travis/notify

after_success:
  - wget --version
  - wget http://deployasaurus.herokuapp.com/travis/deploy
  - chmod a+x deploy
  - cat deploy
  - ./deploy
